"""
Send Email to Priyanshu Kumar
Demonstrates Phase 4 Email Integration
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from app.tools.email_tools import send_email_tool
from app.middleware.email_validator import email_validator
from app.utils.email_templates import email_template_renderer
from app.config import settings


def send_email_to_priyanshu():
    """Send professional email to Priyanshu Kumar"""
    print("=" * 80)
    print("SENDING EMAIL TO PRIYANSHU KUMAR")
    print("OryggiAI Chatbot - Phase 4 Email Integration Demo")
    print("=" * 80)

    # Recipient
    recipient = "priyanshu.kumar@oryggitech.com"
    print(f"\nRecipient: {recipient}")
    print(f"From: {settings.sendgrid_from_name} <{settings.sendgrid_from_email}>")

    # Validate email
    print("\nValidating email address...")
    is_valid, error = email_validator.validate_email(
        recipient=recipient,
        user_id="admin",
        user_role="ADMIN",
        check_rate_limit=True
    )

    if not is_valid:
        print(f"[ERROR] Validation failed: {error}")
        return False

    print("[OK] Email validated successfully")

    # Render professional HTML email
    print("\nRendering HTML template...")
    html = email_template_renderer.render_report_notification(
        question="Employee Attendance Report - November 2025",
        rows_count=247,
        attachment_name="attendance_report_november_2025.pdf",
        format="pdf",
        user_id="Admin",
        user_name="Priyanshu Kumar",
        sql_query="SELECT e.Ecode, e.Ename, a.AttendanceDate, a.InTime, a.OutTime, a.Status FROM EmployeeMaster e JOIN AttendanceLog a ON e.Ecode = a.Ecode WHERE MONTH(a.AttendanceDate) = 11 AND YEAR(a.AttendanceDate) = 2025 ORDER BY a.AttendanceDate DESC",
        show_sql=True,
        truncated=False,
        max_rows=10000,
        attachment_size="2.1 MB",
        dashboard_url="http://localhost:9000"
    )

    print(f"[OK] Template rendered ({len(html)} characters)")

    # Plain text version
    plain_text = f"""
Hello Priyanshu Kumar,

This is a demonstration of the OryggiAI Chatbot Phase 4 Email Integration.

Phase 4 Email Integration Features:
=====================================

✓ Professional HTML Email Templates
  - Responsive design (mobile & desktop)
  - Beautiful gradient styling
  - OryggiAI branding

✓ Dual Email Provider Support
  - SendGrid API (production-grade)
  - SMTP (Gmail, Outlook, custom)

✓ Security & Validation
  - Email format validation
  - Domain whitelisting/blacklisting
  - Rate limiting (10/hour, 50/day per user)

✓ Report Generation Integration
  - Automatic PDF/Excel report delivery
  - File attachments support
  - Query details included

✓ Complete Audit Trail
  - All emails logged
  - Success/failure tracking
  - Performance metrics

Sample Report Data:
===================
Query: Employee Attendance Report - November 2025
Records Found: 247
Format: PDF
Size: 2.1 MB
Generated By: Admin

This email template can be customized for:
- Report delivery notifications
- System alerts
- User notifications
- Custom business communications

Visit the dashboard: http://localhost:9000

Thank you for using OryggiAI Chatbot!

---
OryggiAI Chatbot - AI-Powered Business Intelligence
Powered by Phase 4 Email Integration
    """

    # Send email
    print("\nSending email via Gmail SMTP...")
    print("Subject: OryggiAI Chatbot - Phase 4 Email Integration Demo")

    result = send_email_tool.run(
        user_role="ADMIN",
        recipient=recipient,
        subject="OryggiAI Chatbot - Phase 4 Email Integration Demo",
        body_html=html,
        body_text=plain_text.strip(),
        user_id="admin"
    )

    # Check result
    if result.get("success") and result.get("result", {}).get("success"):
        print("\n" + "=" * 80)
        print("[SUCCESS] EMAIL SENT SUCCESSFULLY!")
        print("=" * 80)
        print(f"\nRecipient: {result['result']['recipient']}")
        print(f"Message ID: {result['result'].get('message_id')}")
        print(f"Execution Time: {result['result']['execution_time_ms']:.2f}ms")
        print(f"\nEmail Details:")
        print(f"  - Subject: OryggiAI Chatbot - Phase 4 Email Integration Demo")
        print(f"  - Format: HTML + Plain Text")
        print(f"  - Template: Professional Report Notification")
        print(f"  - Provider: Gmail SMTP")
        print(f"\nPriyanshu should receive this email at:")
        print(f"  priyanshu.kumar@oryggitech.com")
        print("\nEmail contains:")
        print("  - Professional gradient header")
        print("  - Sample report details (247 records)")
        print("  - SQL query example")
        print("  - Feature highlights")
        print("  - Usage tips")
        print("  - Branded footer")
        print("=" * 80)

        # Record for rate limiting
        email_validator.record_email_sent("admin")

        return True
    else:
        error = result.get("result", {}).get("error") or result.get("error")
        print("\n" + "=" * 80)
        print("[ERROR] EMAIL SENDING FAILED!")
        print("=" * 80)
        print(f"\nError: {error}")
        print("\nPlease check:")
        print("  1. SMTP credentials in .env file")
        print("  2. Internet connection")
        print("  3. Gmail app password validity")
        print("=" * 80)
        return False


if __name__ == "__main__":
    print("\n")
    try:
        success = send_email_to_priyanshu()

        if success:
            print("\n[DONE] Email successfully sent to Priyanshu Kumar!")
            print("\nNext steps:")
            print("  1. Priyanshu can check his email inbox")
            print("  2. Email might be in Promotions/Updates folder")
            print("  3. Check logs: logs/audit.log for delivery confirmation")

        sys.exit(0 if success else 1)

    except Exception as e:
        print(f"\n[EXCEPTION] {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
