"""
Schema Models
SchemaCache - Auto-discovered schema metadata
FewShotExample - Auto-generated Q&A pairs for SQL generation
"""

import uuid
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    Column, String, Integer, Boolean, DateTime,
    Text, ForeignKey, CheckConstraint, DECIMAL, BigInteger
)
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER, NVARCHAR
from sqlalchemy.orm import relationship

from app.models.platform.base import PlatformBase

if TYPE_CHECKING:
    from app.models.platform.database import TenantDatabase


class TableType(str, Enum):
    """Database object types"""
    TABLE = "table"
    VIEW = "view"


class ExampleComplexity(str, Enum):
    """Query complexity levels"""
    SIMPLE = "simple"
    MEDIUM = "medium"
    COMPLEX = "complex"


class ExampleSource(str, Enum):
    """Source of few-shot example"""
    AUTO = "auto"        # Auto-generated by LLM
    MANUAL = "manual"    # Manually added by user
    IMPORTED = "imported"  # Imported from file


class SchemaCache(PlatformBase):
    """
    SchemaCache Model - Stores auto-discovered schema metadata.

    Each record represents a table or view from a tenant's database,
    including column information, sample data, and LLM-generated
    descriptions.
    """

    __tablename__ = "schema_cache"

    # ==================== Database Relationship ====================
    tenant_db_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("tenant_databases.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ==================== Table Information ====================
    table_name = Column(NVARCHAR(255), nullable=False, index=True)
    schema_name = Column(NVARCHAR(128), default="dbo")
    table_type = Column(NVARCHAR(50), default=TableType.TABLE.value)

    # ==================== Column Information (JSON) ====================
    column_info = Column(Text, nullable=False)
    # Format: [{"name": "id", "type": "int", "nullable": false, "pk": true, "fk": null}]

    # ==================== Sample Data (JSON) ====================
    sample_data = Column(Text, nullable=True)
    # Format: [{"col1": "val1", "col2": "val2"}, ...]

    # ==================== Statistics ====================
    row_count = Column(BigInteger, default=0)
    column_count = Column(Integer, default=0)

    # ==================== LLM-Generated Descriptions ====================
    llm_description = Column(Text, nullable=True)
    llm_purpose = Column(NVARCHAR(500), nullable=True)

    # ==================== Module Detection ====================
    detected_module = Column(NVARCHAR(100), nullable=True, index=True)
    confidence_score = Column(DECIMAL(5, 4), nullable=True)  # 0.0000 to 1.0000

    # ==================== Relationships (JSON) ====================
    foreign_keys = Column(Text, nullable=True)
    # Format: [{"column": "dept_id", "references": "departments.id"}]

    referenced_by = Column(Text, nullable=True)
    # Format: [{"table": "employees", "column": "dept_id"}]

    # ==================== Relationships ====================
    tenant_database: "TenantDatabase" = relationship(
        "TenantDatabase",
        back_populates="schema_cache"
    )

    # ==================== Properties ====================
    @property
    def full_name(self) -> str:
        """Get fully qualified table name"""
        return f"{self.schema_name}.{self.table_name}"

    @property
    def is_view(self) -> bool:
        """Check if this is a view"""
        return self.table_type == TableType.VIEW.value

    # ==================== Methods ====================
    def get_columns(self) -> list:
        """Parse and return column info as list"""
        import json
        if self.column_info:
            try:
                return json.loads(self.column_info)
            except json.JSONDecodeError:
                pass
        return []

    def get_column_names(self) -> list:
        """Get list of column names"""
        return [col["name"] for col in self.get_columns()]

    def get_primary_keys(self) -> list:
        """Get list of primary key columns"""
        return [col["name"] for col in self.get_columns() if col.get("pk")]

    def get_sample_rows(self) -> list:
        """Parse and return sample data as list"""
        import json
        if self.sample_data:
            try:
                return json.loads(self.sample_data)
            except json.JSONDecodeError:
                pass
        return []

    def get_foreign_key_info(self) -> list:
        """Parse and return foreign key info"""
        import json
        if self.foreign_keys:
            try:
                return json.loads(self.foreign_keys)
            except json.JSONDecodeError:
                pass
        return []

    def __repr__(self) -> str:
        return (
            f"<SchemaCache(id={self.id}, table='{self.full_name}', "
            f"columns={self.column_count}, rows={self.row_count})>"
        )


class FewShotExample(PlatformBase):
    """
    FewShotExample Model - Auto-generated Q&A pairs for SQL generation.

    Stores question-SQL pairs that are used as few-shot examples
    for the Text-to-SQL system. These are auto-generated during
    onboarding and can be manually curated.
    """

    __tablename__ = "few_shot_examples"

    # ==================== Database Relationship ====================
    tenant_db_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("tenant_databases.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ==================== Q&A Content ====================
    question = Column(Text, nullable=False)
    sql_query = Column(Text, nullable=False)
    explanation = Column(Text, nullable=True)

    # ==================== Categorization ====================
    module = Column(NVARCHAR(100), nullable=True, index=True)
    category = Column(NVARCHAR(100), nullable=True)
    complexity = Column(
        NVARCHAR(20),
        default=ExampleComplexity.MEDIUM.value,
        index=True
    )

    # ==================== Tables Used (JSON) ====================
    tables_used = Column(Text, nullable=True)
    # Format: ["table1", "table2"]

    # ==================== Quality & Status ====================
    is_verified = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True, index=True)
    quality_score = Column(DECIMAL(5, 4), nullable=True)  # 0.0000 to 1.0000

    # ==================== Vector Embedding Reference ====================
    embedding_id = Column(NVARCHAR(255), nullable=True)

    # ==================== Usage Tracking ====================
    usage_count = Column(Integer, default=0)
    success_count = Column(Integer, default=0)
    failure_count = Column(Integer, default=0)
    last_used_at = Column(DateTime, nullable=True)

    # ==================== Generation Source ====================
    source = Column(
        NVARCHAR(50),
        default=ExampleSource.AUTO.value
    )
    generated_by = Column(NVARCHAR(100), nullable=True)  # LLM model name

    # ==================== Relationships ====================
    tenant_database: "TenantDatabase" = relationship(
        "TenantDatabase",
        back_populates="few_shot_examples"
    )

    # ==================== Constraints ====================
    __table_args__ = (
        CheckConstraint(
            complexity.in_([c.value for c in ExampleComplexity]),
            name="CHK_few_shot_examples_complexity"
        ),
        CheckConstraint(
            source.in_([s.value for s in ExampleSource]),
            name="CHK_few_shot_examples_source"
        ),
    )

    # ==================== Properties ====================
    @property
    def success_rate(self) -> float:
        """Calculate success rate"""
        total = self.success_count + self.failure_count
        if total == 0:
            return 0.0
        return self.success_count / total

    @property
    def is_high_quality(self) -> bool:
        """Check if example is high quality"""
        return (
            self.is_verified and
            self.quality_score is not None and
            float(self.quality_score) >= 0.8
        )

    # ==================== Methods ====================
    def get_tables(self) -> list:
        """Parse and return tables used as list"""
        import json
        if self.tables_used:
            try:
                return json.loads(self.tables_used)
            except json.JSONDecodeError:
                pass
        return []

    def record_usage(self, success: bool) -> None:
        """Record usage of this example"""
        self.usage_count += 1
        self.last_used_at = datetime.utcnow()

        if success:
            self.success_count += 1
        else:
            self.failure_count += 1

    def verify(self, score: float = None) -> None:
        """Mark example as verified"""
        self.is_verified = True
        if score is not None:
            self.quality_score = score

    def deactivate(self) -> None:
        """Deactivate example"""
        self.is_active = False

    def to_training_format(self) -> dict:
        """Convert to format suitable for RAG/embedding"""
        return {
            "id": str(self.id),
            "question": self.question,
            "sql": self.sql_query,
            "module": self.module,
            "tables": self.get_tables(),
            "complexity": self.complexity
        }

    def __repr__(self) -> str:
        return (
            f"<FewShotExample(id={self.id}, module='{self.module}', "
            f"complexity='{self.complexity}', verified={self.is_verified})>"
        )
